### ISSUE TITLE
加载JS文件的地方，在springboot和tomcat中使用，有测试过吗？

### ISSUE THREAD

**Issue by doobo** [antherd/sm-crypto#1]
加载JS文件，感觉在springboot打包成jar运行时读取不到文件，不过非常了不起，我也是才知道JDK1.8可用运行JS脚本，思路奇特，大佬有sm2加解密的性能测试数据吗？

**Comment by geyiwei-suzhou** [comment]
资源文件想要在jar包中读取，应该使用ClassLoader方式加载静态文件，本项目中也是通过ClassLoader方式加载的。性能在Test类中有简单计算加解密时间，可以自行测试一下。

**Comment by geyiwei-suzhou** [comment]
> 加载JS文件，感觉在springboot打包成jar运行时读取不到文件，不过非常了不起，我也是才知道JDK1.8可用运行JS脚本，思路奇特，大佬有sm2加解密的性能测试数据吗？
资源文件想要在jar包中读取，应该使用ClassLoader方式加载静态文件，本项目中也是通过ClassLoader方式加载的。性能在Test类中有简单计算加解密时间，可以自行测试一下。

**Comment by geyiwei-suzhou** [comment]
> 加载JS文件，感觉在springboot打包成jar运行时读取不到文件，不过非常了不起，我也是才知道JDK1.8可用运行JS脚本，思路奇特，大佬有sm2加解密的性能测试数据吗？

资源文件想要在jar包中读取，应该使用ClassLoader方式加载静态文件，本项目中也是通过ClassLoader方式加载的。性能在Test类中有简单计算加解密时间，可以自行测试一下。
