### ISSUE TITLE
性能优化建议

### ISSUE THREAD

**Issue by zxy1559761282** [antherd/sm-crypto#16]
java  0.3.2版 在6核12线程 基础频率 2.5ghz cpu 上 sm2解密耗时 160ms - 220 ms ， 有空能不能提升一下性能，拜托了， 谢谢！

**Comment by geyiwei-hub** [comment]
> java 0.3.2版 在6核12线程 基础频率 2.5ghz cpu 上 sm2解密耗时 160ms - 220 ms ， 有空能不能提升一下性能，拜托了， 谢谢！

等空了可以优化一下，不过封装js版本毕竟比不上原生。优化空间估计也有限。欢迎提pull requests.
