### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by chibaolai** [antherd/sm-crypto#18]
SM4 c# 加密，java解密，可以正常解密，但是中文存在乱码

**Comment by zhongbiran** [comment]
> SM4 c# 加密，java解密，可以正常解密，但是中文存在乱码

老哥，你解决了吗？

**Comment by chibaolai** [comment]
解决了，是编码问题，getByte 使用utf-8




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年05月18日 11:35 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
State ***@***.***> |
| 主题 | Re: [antherd/sm-crypto] 中文乱码 (Issue #18) |

SM4 c# 加密，java解密，可以正常解密，但是中文存在乱码

老哥，你解决了吗？
