### ISSUE TITLE
默认userid 加上私钥私用sm2签名跟医保局的对不上= = 好难受！ 

### ISSUE THREAD

**Issue by yuqi118** [antherd/sm-crypto#2]
医保局的要求是将签名返回的字节码进行base64编码，我把string转字节后编码的 ，怎么也不对，作者能帮忙吗 联系方式 13104690 (qq微信都是这个)

**Comment by geyiwei-suzhou** [comment]
医保局使用的是哪个sm加密库，建议使用同一套库加解密

**Comment by geyiwei-suzhou** [comment]
> 医保局的要求是将签名返回的字节码进行base64编码，我把string转字节后编码的 ，怎么也不对，作者能帮忙吗 联系方式 13104690 (qq微信都是这个)

医保局使用的是哪个sm加密库，建议使用同一套库加解密。string转字节的时候注意进制问题，一般是16进制。
