### ISSUE TITLE
为什么这个验签比bcprov-jdk慢至少2秒？

### ISSUE THREAD

**Issue by usermtl** [antherd/sm-crypto#21]
为什么这个验签比bcprov-jdk慢至少2秒？

**Comment by Tyler-Rabbit** [comment]
是用javax.script.ScriptEngine调用的js版本的国密算法加解密，性能差点

**Comment by geyiwei-hub** [comment]
> 为什么这个验签比bcprov-jdk慢至少2秒？

如上回答。
