### ISSUE TITLE
SM3摘要带公钥和UserId

### ISSUE THREAD

**Issue by 1798972** [antherd/sm-crypto#4]
您好,能扩展下SM3摘要带公钥和UserId的实现吗?

**Comment by geyiwei-suzhou** [comment]
> 您好,能扩展下SM3摘要带公钥和UserId的实现吗?

你好，SM3算法只是把String算出一个杂凑（Hash）的作用，带公钥和UserId的方式不太理解。是不是业务有要求生成杂凑时需要添加公钥和UserId进去？如果是，可以把公钥、UserId和业务数据放到一起toString()一下，然后算SM3
