### ISSUE TITLE
encrypt decrypt time very long

### ISSUE THREAD

**Issue by PretendMask** [antherd/sm-crypto#5]
public static void main(String[] args) {
        String msg = "159";
        // 16 进制字符串，要求为 128 比特
        String key = "3124456789abcdeffedcba9876543210";
        // 加密，默认使用 pkcs#5 填充，输出16进制字符串
        long ens = System.currentTimeMillis();
        String encryptData1 = Sm4.encrypt(msg, key);
        long ene = System.currentTimeMillis();
        System.out.println("encrypt 1 ： " + encryptData1);
        // 解密，默认使用 pkcs#5 填充，输出 utf8 字符串
        long des = System.currentTimeMillis();
        String decryptData1 = Sm4.decrypt(encryptData1, key);
        long dee = System.currentTimeMillis();
        System.out.println("decrypt 1 ： " + decryptData1);
        System.out.println("encrypt time：" + (dee - des) + "ms" + ". decrypt time：" + (ene-ens) + "ms");
    }
out result：
encrypt 1 ： a3121e371c1da5e7237d7b18305ce6fd
decrypt 1 ： 159
encrypt time：139ms. decrypt time：2582ms

**Comment by antherd-admin** [comment]
You can preload the classes in you programs to reduce the processing time.
Example:
```java
    public static void main(String[] args) {
//        Sm4 sm4 = new Sm4();
        String msg = "159";
        String key = "3124456789abcdeffedcba9876543210";
        long ens = System.currentTimeMillis();
        Sm4.encrypt(msg, key);
        long ene = System.currentTimeMillis();
        System.out.println("encrypt time：" + (ene - ens) + "ms"); // encrypt time：1098ms
    }
```
vs
```java
    public static void main(String[] args) {
        Sm4 sm4 = new Sm4();
        String msg = "159";
        String key = "3124456789abcdeffedcba9876543210";
        long ens = System.currentTimeMillis();
        Sm4.encrypt(msg, key);
        long ene = System.currentTimeMillis();
        System.out.println("encrypt time：" + (ene - ens) + "ms"); // encrypt time：253ms
    }
```
