### ISSUE TITLE
SM2椭圆曲线参数

### ISSUE THREAD

**Issue by XinwenXiang** [antherd/sm-crypto#7]
你好，想请问SM2使用的椭圆曲线方程和安全参数，在Java版本中的SM2代码部分没看见。

**Comment by antherd-admin** [comment]
内部椭圆曲线方程直接调用的是js的方程。生成椭圆曲线方程可以参考js版本。
这个java版本更多关注的是应用，没有深入到内部算法，如果想改造内部算法，可以把js版本修改之后重新打包，替换掉这个项目里的js文件即可。
 Sm2.getPoint() 方法获取椭圆曲线点。
安全参数您指的是哪一方面？

**Comment by XinwenXiang** [comment]
感谢您的回答，已在js版本代码sm2下的ec.js查看到。
按照个人理解，安全性应和椭圆曲线方程的选取和曲线参数有关，SM2算法有推荐值，如果您有兴趣可参考oscca.gov.cn的内容。
谢谢
