### ISSUE TITLE
加密解密速度太慢

### ISSUE THREAD

**Issue by Montaro2017** [antherd/sm-crypto#8]
简单加密一下居然要花接近4s
```java
@Test
public void testSm2Encrypt() {
    String data = "{\"abc\":123}";
    String publicKey = "041130412b93ca6ba1b7143d821d363fa12a98bc093dd324e5f47ca7401a75cb8cd098851f40852b5193ca31203f34cc24548dc51ca409933e1d0cd30e4cea6e05";
    String privateKey = "16c8160303ed9cf0af3c8d61f93be5e091c2115276bc9152a9cfe2d7b6a903bc";
    Long before = System.currentTimeMillis();
    String encrypt = Sm2.doEncrypt(data, publicKey);
    Long after = System.currentTimeMillis();
    System.out.println("加密 " + (after - before) + " ms");
    System.out.println("encrypt = " + encrypt);
    before = System.currentTimeMillis();
    String decrypt = Sm2.doDecrypt(encrypt, privateKey);
    after = System.currentTimeMillis();
    System.out.println("解密 " + (after - before) + " ms");
    System.out.println("decrypt = " + decrypt);
}
```

这是输出结果
![image](https://user-images.githubusercontent.com/35142778/169227727-720a0daf-cb34-406f-b6e2-993669734e5d.png)

使用其他第三方的库对相同数据进行加密只需要大约15ms左右

**循环10次测试发现也要大约100-300ms左右**

**Comment by antherd-admin** [comment]
> 简单加密一下居然要花接近4s
> 
> ```java
> @Test
> public void testSm2Encrypt() {
>     String data = "{\"abc\":123}";
>     String publicKey = "041130412b93ca6ba1b7143d821d363fa12a98bc093dd324e5f47ca7401a75cb8cd098851f40852b5193ca31203f34cc24548dc51ca409933e1d0cd30e4cea6e05";
>     String privateKey = "16c8160303ed9cf0af3c8d61f93be5e091c2115276bc9152a9cfe2d7b6a903bc";
>     Long before = System.currentTimeMillis();
>     String encrypt = Sm2.doEncrypt(data, publicKey);
>     Long after = System.currentTimeMillis();
>     System.out.println("加密 " + (after - before) + " ms");
>     System.out.println("encrypt = " + encrypt);
>     before = System.currentTimeMillis();
>     String decrypt = Sm2.doDecrypt(encrypt, privateKey);
>     after = System.currentTimeMillis();
>     System.out.println("解密 " + (after - before) + " ms");
>     System.out.println("decrypt = " + decrypt);
> }
> ```
> 
> 这是输出结果 ![image](https://user-images.githubusercontent.com/35142778/169227727-720a0daf-cb34-406f-b6e2-993669734e5d.png)
> 
> 使用其他第三方的库对相同数据进行加密只需要大约15ms左右
> 
> **循环10次测试发现也要大约100-300ms左右**

你好，这个代码库是移植版，主要通过Java框架中的js引擎加载原生js文件进行调用。主要耗时在于文件加载的过程。可以参考这个[issue ](https://github.com/antherd/sm-crypto/issues/5)优化应用代码，或者寻找其他第三方兼容库。也欢迎其他大佬优化提pr。

**Comment by Montaro2017** [comment]
已使用hutool解决
